### ISSUE TITLE
Drush 9 freaks out when using symlink

### ISSUE THREAD

**Issue by bpresles** [webflo/drupal-finder#34] opened 2017-10-25 20:36 UTC
I first reported this issue on Drush (see: https://github.com/drush-ops/drush/issues/3098), but according to @weitzman, it's related to drupal-finder, that's why I open a new issue here. 

Drush version used: Drush 9.0.0-beta7 (and reproduced also on beta 5 or 6)

With some structure, like the one used by Ansistrano, when we launch drush, it spawn processes indefinitely.

Example structure:

/srv/www/releases/mysite_1.0.2
/srv/www/current -> /srv/www/releases/mysite_1.0.2 (i.e: current is a symlink on mysite_1.0.2)

Inside the mysite_0.2 the Drupal is installed as follow:

- src/ (contains composer.json (and .lock) for all the project dependencies (drupal modules and others dependencies)
- src/web (Drupal root).

The core and modules are installed via Composer using composer/installers and the following installer paths, and Drupal Scaffold:

> "installer-paths":
>  {
>       "drush/contrib/{$name}": [
>         "type:drupal-drush"
>       ],
>       "web/core": [
>         "type:drupal-core"
>       ],
>       "web/libraries/{$name}": [
>         "type:drupal-library"
>       ],
>       "web/modules/contrib/{$name}": [
>         "type:drupal-module"
>       ],
>       "web/profiles/contrib/{$name}": [
>         "type:drupal-profile"
>       ],
>       "web/themes/contrib/{$name}": [
>         "type:drupal-theme"
>       ]
> },

In this configuration, when we go in /srv/www/current/src/web (drupal root) and type for example "drush status", it nevers return anything and if we do a "ps aux | grep drush" we see numerous drush processes (increasing rapidly) being spawn.

If we go to the /srv/www/releases/mysite_0.2/src/web directory instead (so not using the symlink), it works just fine.

Current workaround so: either go to the original directory (not the symlink) or specify the real path using --root drush option.

**Comment by webflo** [comment] 2017-10-25 20:48
Its the symlink relative or absolute? Could you try to run it from src, not web as well? Thanks!

**Comment by webflo** [comment] 2017-10-25 21:07
Are you using the drush-launcher as global executable or another drush version?

**Comment by segi** [comment] 2017-10-26 12:29
So I faced with the same problem and we were redirected from drush repo to here. 
Currently I'm running the next command which isn't working: 
`drush -r '/folder-symlink/docroot' version` where folder-symlink -> folder is a symlink.

Isn't working as well:
`drush -r '/folder-symlink/`

I found that only working solution is:
`drush -r '/folder-symlink version'`

The problem in DrupalFinder->locateRoot() method: 
`if ($follow_symlinks && is_link($path)) {
    $path = realpath($path);
 }`

So, is_link only true if I use folder-symlink without slash. I tested that the realpath() is working for /folder-symlink/docroot as well. The current solution isn't a bulletproof solution but I don't wanna say it's problem of this lib.

Currently if I use the first solution will cause infinite loop in drush call, but If I use third one it won't find the drush under /folder-symlink/docroot/vendor.

I'm using absolute path everywhere.

**Comment by rmuit** [comment] 2017-10-26 12:58
Ignorant quick comment from the sidelines (without testing code or even looking at it, only listening to segi explain):

It sounded like this is caused by the 'end' folder/filename not being a symlink, but some other part of the path being a symlink.

Practical example (garbled, not completely true but you get the gist)
Acquia hosting has paths /var/www/SITENAME/(docroot|vendor), which contains drush
But /var/www/SITENAME is actually a symlink to CUSTOMERALIAS.
Yet we are somehow administratively required to use /var/www/SITENAME/vendor/whatever in our scripts.

And it sounds like the fact that the _real_ name of /var/www/SITENAME/vendor/whatever is actually /var/www/CUSTOMERALIAS/vendor/whatever, is somehow causing infinite loops.

**Comment by webflo** [comment] 2017-10-26 14:57
Hmm the bug reports are not detailed enough yet. Its still not clear if the "drush" executable is Drush 8, 9 or the Drush Launcher. Ideally would be if this is reproducible in a simple script which only involves the drupal-finder library.

**Comment by webflo** [comment] 2017-10-26 15:04
Please try this script for debugging. https://gist.github.com/webflo/321e148851048c8cdb346a675f27d2ce

**Comment by segi** [comment] 2017-11-21 12:53
The issue will fixed in https://github.com/drush-ops/drush/pull/3110

**Comment by webflo** [comment] 2018-07-04 20:41
Thx

**Closed by webflo** 2018-07-04 20:41 UTC
